.TH "pdf180" "1" "10 March 2010" "" "" 
.SH "NAME" 
pdf180 \- rotate the pages of pdf files
.SH "SYNOPSIS" 
.PP 
pdf180 [OPTION [OPTION] \&.\&.\&.] [SRC [PAGESPEC] [SRC [PAGESPEC]] \&.\&.\&.] 
.PP 
.SH "DESCRIPTION" 
.PP 
pdf180 rotates the pages of files in the Adobe Portable Document Format (PDF)
through 180 degrees\&.  
.PP
If no source PDF file ('SRC') is specified, input
is from /dev/stdin. If 'PAGESPEC' is omitted, all pages are processed.
.PP
Source files are processed sequentially into a single output
unless the '--batch' option is used, in which case they are processed 
separately.
.PP 
pdf180 operates on one or more PDF files, and (either with the '--batch' 
option or with '--outfile DIR' where 'DIR' is a directory) the 
resulting files have
the suffix '-rotated180' applied to their names by default.  To change 
the suffix,
use the '--suffix' option, for example
.PP
.RS
.B    pdf180 --suffix 'upturned' --batch myfile1.pdf myfile2.pdf
.RE
.PP 
will result in files named 'myfile1-upturned.pdf' and 'myfile2-upturned.pdf'.
.PP 
pdf180 is a simple wrapper for pdfjam, which is a front end to many of the capabilities of the pdfpages
package for pdflatex\&.  A working installation of pdflatex with
the pdfpages package is required\&.
.PP 
pdf180 was formerly part of the "PDFjam" package of tools&.
.PP
.SH "USAGE" 
.PP 
For the available options and site/user defaults, see the output of 
.PP
.RS
    pdfjam --help
.RE
.PP
.SH "LIMITATIONS AND BUGS" 
.PP
pdf180 does not work with encrypted PDF files, and does not 
preserve hyperlinks.
.PP 
.SH "SEE ALSO" 
.PP 
pdfjam(1)\&.
.PP 
.SH "LICENSE" 
.PP 
pdf180 is distributed under the GNU public license\&. 
.PP 
.SH "AUTHOR" 
.PP 
pdf180 was written originally by David Firth as part of the PDFjam package\&.

