.TH "pdfjoin" "1" "10 March 2010" "" "" 
.SH "NAME" 
pdfjoin 
\- join together pages from multiple PDF files
.SH "SYNOPSIS" 
.PP 
.B pdfjoin [OPTION [OPTION] \&.\&.\&.] [SRC [PAGESPEC] [SRC [PAGESPEC]] \&.\&.\&.]
.PP 
.SH "DESCRIPTION" 
.PP 
pdfjoin 
concatenates the pages of multiple Portable Document Format (PDF)
files together into a single file.\&.  
.PP
If no source PDF file ('SRC') is specified, input (but just one file -- not
very useful here!
is from /dev/stdin. If 'PAGESPEC' is omitted, all pages are processed.
.PP
Source files are processed sequentially into a single output.
The '--batch' option of pdfjam(1) cannot be used.
.PP 
pdfjoin is a simple wrapper for pdfjam, which provides a front end to many of the capabilities of the pdfpages
package for pdflatex\&.  A working installation of pdflatex, with
the pdfpages package, is required\&.
.PP 
pdfjoin was formerly part of the "PDFjam" package of tools\&.
.PP
.SH "USAGE" 
.PP 
For the available options and site/user defaults, see the output of 
.PP
.RS
.B   pdfjam --help
.RE
.PP
.SH "LIMITATIONS AND BUGS" 
.PP
The pages of the output file will all have the same size and orientation.
.PP
pdfjoin does not work with encrypted PDF files, and does not 
preserve hyperlinks.  The output pages are all one size.
.PP 
.SH "LICENSE" 
.PP 
pdfjoin is distributed under the GNU public license\&. 
.PP 
.SH "SEE ALSO" 
.PP 
pdfjam(1)\&.
.PP 
.SH "AUTHOR" 
.PP 
pdfjoin was written originally by David Firth as part of the PDFjam 
package\&.

